//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceBase
{
    
    System.Data.DataTable GetDt(string sql);
    
    System.Data.DataTable GetDtByCommond(string sql);
    
    System.Data.DataTable GetDtSap(string sql);
    
    Result RunSql(string sql);
    
    Result RunSqlSap(string sql);
    
    Result RunSqls(string[] Sqls);
    
    Result RunSqlsSap(string[] Sqls);
    
    Result Insert(string sql);
    
    Result RunScalar(string sql);
    
    Result SaveImage(string tableName, string fieldName, byte[] image, string PK, string PKValue);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDt", Namespace="http://tempuri.org/")]
public partial class GetDtRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public GetDtRequest()
    {
    }
    
    public GetDtRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDtResponse", Namespace="http://tempuri.org/")]
public partial class GetDtResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataTable GetDtResult;
    
    public GetDtResponse()
    {
    }
    
    public GetDtResponse(System.Data.DataTable GetDtResult)
    {
        this.GetDtResult = GetDtResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDtByCommond", Namespace="http://tempuri.org/")]
public partial class GetDtByCommondRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public GetDtByCommondRequest()
    {
    }
    
    public GetDtByCommondRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDtByCommondResponse", Namespace="http://tempuri.org/")]
public partial class GetDtByCommondResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataTable GetDtByCommondResult;
    
    public GetDtByCommondResponse()
    {
    }
    
    public GetDtByCommondResponse(System.Data.DataTable GetDtByCommondResult)
    {
        this.GetDtByCommondResult = GetDtByCommondResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDtSap", Namespace="http://tempuri.org/")]
public partial class GetDtSapRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public GetDtSapRequest()
    {
    }
    
    public GetDtSapRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetDtSapResponse", Namespace="http://tempuri.org/")]
public partial class GetDtSapResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataTable GetDtSapResult;
    
    public GetDtSapResponse()
    {
    }
    
    public GetDtSapResponse(System.Data.DataTable GetDtSapResult)
    {
        this.GetDtSapResult = GetDtSapResult;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PlatformServer")]
public partial class Result
{
    
    private string messageField;
    
    private int statusField;
    
    private bool statusFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified
    {
        get
        {
            return this.statusFieldSpecified;
        }
        set
        {
            this.statusFieldSpecified = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSql", Namespace="http://tempuri.org/")]
public partial class RunSqlRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public RunSqlRequest()
    {
    }
    
    public RunSqlRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqlResponse", Namespace="http://tempuri.org/")]
public partial class RunSqlResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result RunSqlResult;
    
    public RunSqlResponse()
    {
    }
    
    public RunSqlResponse(Result RunSqlResult)
    {
        this.RunSqlResult = RunSqlResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqlSap", Namespace="http://tempuri.org/")]
public partial class RunSqlSapRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public RunSqlSapRequest()
    {
    }
    
    public RunSqlSapRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqlSapResponse", Namespace="http://tempuri.org/")]
public partial class RunSqlSapResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result RunSqlSapResult;
    
    public RunSqlSapResponse()
    {
    }
    
    public RunSqlSapResponse(Result RunSqlSapResult)
    {
        this.RunSqlSapResult = RunSqlSapResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqls", Namespace="http://tempuri.org/")]
public partial class RunSqlsRequest
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] Sqls;
    
    public RunSqlsRequest()
    {
    }
    
    public RunSqlsRequest(string[] Sqls)
    {
        this.Sqls = Sqls;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqlsResponse", Namespace="http://tempuri.org/")]
public partial class RunSqlsResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result RunSqlsResult;
    
    public RunSqlsResponse()
    {
    }
    
    public RunSqlsResponse(Result RunSqlsResult)
    {
        this.RunSqlsResult = RunSqlsResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqlsSap", Namespace="http://tempuri.org/")]
public partial class RunSqlsSapRequest
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] Sqls;
    
    public RunSqlsSapRequest()
    {
    }
    
    public RunSqlsSapRequest(string[] Sqls)
    {
        this.Sqls = Sqls;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunSqlsSapResponse", Namespace="http://tempuri.org/")]
public partial class RunSqlsSapResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result RunSqlsSapResult;
    
    public RunSqlsSapResponse()
    {
    }
    
    public RunSqlsSapResponse(Result RunSqlsSapResult)
    {
        this.RunSqlsSapResult = RunSqlsSapResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="Insert", Namespace="http://tempuri.org/")]
public partial class InsertRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public InsertRequest()
    {
    }
    
    public InsertRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="InsertResponse", Namespace="http://tempuri.org/")]
public partial class InsertResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result InsertResult;
    
    public InsertResponse()
    {
    }
    
    public InsertResponse(Result InsertResult)
    {
        this.InsertResult = InsertResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunScalar", Namespace="http://tempuri.org/")]
public partial class RunScalarRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string sql;
    
    public RunScalarRequest()
    {
    }
    
    public RunScalarRequest(string sql)
    {
        this.sql = sql;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="RunScalarResponse", Namespace="http://tempuri.org/")]
public partial class RunScalarResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result RunScalarResult;
    
    public RunScalarResponse()
    {
    }
    
    public RunScalarResponse(Result RunScalarResult)
    {
        this.RunScalarResult = RunScalarResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="SaveImage", Namespace="http://tempuri.org/")]
public partial class SaveImageRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string tableName;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=1)]
    public string fieldName;
    
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Namespace="http://tempuri.org/", Order=2)]
    public byte[] image;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=3)]
    public string PK;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=4)]
    public string PKValue;
    
    public SaveImageRequest()
    {
    }
    
    public SaveImageRequest(string tableName, string fieldName, byte[] image, string PK, string PKValue)
    {
        this.tableName = tableName;
        this.fieldName = fieldName;
        this.image = image;
        this.PK = PK;
        this.PKValue = PKValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="SaveImageResponse", Namespace="http://tempuri.org/")]
public partial class SaveImageResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result SaveImageResult;
    
    public SaveImageResponse()
    {
    }
    
    public SaveImageResponse(Result SaveImageResult)
    {
        this.SaveImageResult = SaveImageResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceBaseClient : Microsoft.Tools.ServiceModel.CFClientBase<IServiceBase>, IServiceBase
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://218.91.152.186:8045/ServiceBase.svc");
    
    public ServiceBaseClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public ServiceBaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private GetDtResponse GetDt(GetDtRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/GetDt";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/GetDtResponse";
        info.ResponseIsWrapped = true;
        GetDtResponse retVal = base.Invoke<GetDtRequest, GetDtResponse>(info, request);
        return retVal;
    }
    
    public System.Data.DataTable GetDt(string sql)
    {
        GetDtRequest request = new GetDtRequest(sql);
        GetDtResponse response = this.GetDt(request);
        return response.GetDtResult;
    }
    
    private GetDtByCommondResponse GetDtByCommond(GetDtByCommondRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/GetDtByCommond";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/GetDtByCommondResponse";
        info.ResponseIsWrapped = true;
        GetDtByCommondResponse retVal = base.Invoke<GetDtByCommondRequest, GetDtByCommondResponse>(info, request);
        return retVal;
    }
    
    public System.Data.DataTable GetDtByCommond(string sql)
    {
        GetDtByCommondRequest request = new GetDtByCommondRequest(sql);
        GetDtByCommondResponse response = this.GetDtByCommond(request);
        return response.GetDtByCommondResult;
    }
    
    private GetDtSapResponse GetDtSap(GetDtSapRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/GetDtSap";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/GetDtSapResponse";
        info.ResponseIsWrapped = true;
        GetDtSapResponse retVal = base.Invoke<GetDtSapRequest, GetDtSapResponse>(info, request);
        return retVal;
    }
    
    public System.Data.DataTable GetDtSap(string sql)
    {
        GetDtSapRequest request = new GetDtSapRequest(sql);
        GetDtSapResponse response = this.GetDtSap(request);
        return response.GetDtSapResult;
    }
    
    private RunSqlResponse RunSql(RunSqlRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/RunSql";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/RunSqlResponse";
        info.ResponseIsWrapped = true;
        RunSqlResponse retVal = base.Invoke<RunSqlRequest, RunSqlResponse>(info, request);
        return retVal;
    }
    
    public Result RunSql(string sql)
    {
        RunSqlRequest request = new RunSqlRequest(sql);
        RunSqlResponse response = this.RunSql(request);
        return response.RunSqlResult;
    }
    
    private RunSqlSapResponse RunSqlSap(RunSqlSapRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/RunSqlSap";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/RunSqlSapResponse";
        info.ResponseIsWrapped = true;
        RunSqlSapResponse retVal = base.Invoke<RunSqlSapRequest, RunSqlSapResponse>(info, request);
        return retVal;
    }
    
    public Result RunSqlSap(string sql)
    {
        RunSqlSapRequest request = new RunSqlSapRequest(sql);
        RunSqlSapResponse response = this.RunSqlSap(request);
        return response.RunSqlSapResult;
    }
    
    private RunSqlsResponse RunSqls(RunSqlsRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/RunSqls";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/RunSqlsResponse";
        info.ResponseIsWrapped = true;
        RunSqlsResponse retVal = base.Invoke<RunSqlsRequest, RunSqlsResponse>(info, request);
        return retVal;
    }
    
    public Result RunSqls(string[] Sqls)
    {
        RunSqlsRequest request = new RunSqlsRequest(Sqls);
        RunSqlsResponse response = this.RunSqls(request);
        return response.RunSqlsResult;
    }
    
    private RunSqlsSapResponse RunSqlsSap(RunSqlsSapRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/RunSqlsSap";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/RunSqlsSapResponse";
        info.ResponseIsWrapped = true;
        RunSqlsSapResponse retVal = base.Invoke<RunSqlsSapRequest, RunSqlsSapResponse>(info, request);
        return retVal;
    }
    
    public Result RunSqlsSap(string[] Sqls)
    {
        RunSqlsSapRequest request = new RunSqlsSapRequest(Sqls);
        RunSqlsSapResponse response = this.RunSqlsSap(request);
        return response.RunSqlsSapResult;
    }
    
    private InsertResponse Insert(InsertRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/Insert";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/InsertResponse";
        info.ResponseIsWrapped = true;
        InsertResponse retVal = base.Invoke<InsertRequest, InsertResponse>(info, request);
        return retVal;
    }
    
    public Result Insert(string sql)
    {
        InsertRequest request = new InsertRequest(sql);
        InsertResponse response = this.Insert(request);
        return response.InsertResult;
    }
    
    private RunScalarResponse RunScalar(RunScalarRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/RunScalar";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/RunScalarResponse";
        info.ResponseIsWrapped = true;
        RunScalarResponse retVal = base.Invoke<RunScalarRequest, RunScalarResponse>(info, request);
        return retVal;
    }
    
    public Result RunScalar(string sql)
    {
        RunScalarRequest request = new RunScalarRequest(sql);
        RunScalarResponse response = this.RunScalar(request);
        return response.RunScalarResult;
    }
    
    private SaveImageResponse SaveImage(SaveImageRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IServiceBase/SaveImage";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IServiceBase/SaveImageResponse";
        info.ResponseIsWrapped = true;
        SaveImageResponse retVal = base.Invoke<SaveImageRequest, SaveImageResponse>(info, request);
        return retVal;
    }
    
    public Result SaveImage(string tableName, string fieldName, byte[] image, string PK, string PKValue)
    {
        SaveImageRequest request = new SaveImageRequest(tableName, fieldName, image, PK, PKValue);
        SaveImageResponse response = this.SaveImage(request);
        return response.SaveImageResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://tempuri.org/IServiceBase/GetDt", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/GetDt", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/GetDtByCommond", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/GetDtByCommond", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/GetDtSap", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/GetDtSap", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSql", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSql", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSqlSap", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSqlSap", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSqls", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSqls", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSqlsSap", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunSqlsSap", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/Insert", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/Insert", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunScalar", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/RunScalar", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/SaveImage", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IServiceBase/SaveImage", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://tempuri.org/IServiceBase/GetDtResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/GetDtResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/GetDtByCommondResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/GetDtByCommondResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/GetDtSapResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/GetDtSapResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlSapResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlSapResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlsResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlsResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlsSapResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunSqlsSapResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/InsertResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/InsertResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunScalarResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/RunScalarResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/SaveImageResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IServiceBase/SaveImageResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
